# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '3.1'

services:

  # drupal_dc will also be DNS name
  drupal_dc:
    image: drupal:8-apache
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes

      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /var/www/html/sites
    restart: always
  
  #postgres_dc will also be DNS name
  postgres_dc:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: password
    restart: always

# named volumes
volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes: